dist: bionic
language: cpp
git:
  depth: false # clone the whole SCM history for sonarqubes' benefit when computing blame data
addons:
  sonarcloud:
    organization: "wispacerace"
    token:
      secure: "QAWnQ1wq1rgK/z19YireiB3CZqvi6WB7Urp5d7UVN39ADsq5dvos2XnvXrfmVETEDfOi2i/bYTPfTpxhHw9NMFCzhedL9kltbiA0W4Yl130h3BStgHoinNRoWc214mtalKGw4ooHnIaq53qmAaj5nxS56yBmw4r8mUae0oo6NnLGMQqFncwaP6sTJYjsDCaMGv9OVt1D9BznJYvgOp9A4QtRF8mWRVy1nkW0xw9uD7+5dmBn3EtqSdFmBdcPxTXJ9EFyi03TnMrsjr/OavASMU/8SV7BjC++rgJVkDBXRhSRno7OvRDS92QVpiwenl/k4VQJwbXLgFLJgmKZ2B32ACfDaS1CLZ4nfzoPavC0Nx7/IkW0gEyRe4CVWEPvpBOVLsem4O4iwjG46XA71LYPkj1hv3AUKxI+uuWBb+NRW5usbf0t2E/IgAzRA/gWcK/HeBTJJMit0+KitrX7H2YlxfHDdI7uE4cX1sXyoY+pYdb27evNppfPjYxldrR6SgU8fxBcm4aRPBds11BCoYrUE/JVVi9wkmGrgz2ezgpMq/Ma/0lkzJ4m7SbavdJuOxJGvk/gQgIyIB07pMCpM3nuoV8HCVewxH6XZwvA2qZ7qxJ2a47mXOGKCUptnOsQxjZ5QrNnjQ47e2YLakRbYJfzXD24G6bJHQegTEeGuPfKR7Q="

install:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 -O ~/toolchain.tar.bz2
  - tar xvf ~/toolchain.tar.bz2 -C ~/
  - wget -qO- "https://cmake.org/files/v3.15/cmake-3.15.3-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C ~/.local
  - export PATH=~/.local/bin:$PATH

script:
  # attempt to hack around glib bug that makes sonar unhappy
  - INTERCEPTOR_LIB=`find ${TRAVIS_HOME} -name libinterceptor-x86_64.so`
  - INTERCEPTOR_LINK=`sed "s/x86_64/haswell/g"<<<"$INTERCEPTOR_LIB"`
  - ln -s $INTERCEPTOR_LIB $INTERCEPTOR_LINK || true

  - mkdir -p build; cd build; cmake -DTOOLCHAIN_PATH=~/gcc-arm-none-eabi-8-2019-q3-update ..; cd ..
  - mkdir -p build-testing; cd build-testing; cmake -DTESTS=ON ..; cd ..
  - build-wrapper-linux-x86-64 --out-dir bw-output make -C build
  - make -C build-testing test-fcu
  
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'